service: serverless-chrome-package-lambda-test

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  environment:
    DEBUG: "*"

package:
  exclude:
    - ./**

  include:
    - node_modules/chrome-launcher/**
    - node_modules/@types/**
    - node_modules/mkdirp/**
    - node_modules/minimist/**
    - node_modules/rimraf/**
    - node_modules/glob/**
    - node_modules/fs.realpath/**
    - node_modules/inflight/**
    - node_modules/inherits/**
    - node_modules/minimatch/**
    - node_modules/once/**
    - node_modules/path-is-absolute/**
    - node_modules/brace-expansion/**
    - node_modules/concat-map/**
    - node_modules/balanced-match/**
    - node_modules/wrappy/**
    - node_modules/lighthouse/lighthouse-core/lib/**
    - node_modules/debug/**
    - dist/**
    - test/handler.js
    - headless_shell
    - libosmesa.so

functions:
  test:
    description: serverless-chrome/lambda test
    memorySize: 1536
    timeout: 30
    handler: test/handler.run

    events:
      - http:
          path: package/lambda/test
          method: get
