service: serverless-chrome-example

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  environment:
    LOGGING: true

functions:
  versionInfo:
    description: Headless Chrome Serverless-framework version info example
    memorySize: 1536
    timeout: 30
    handler: handlers.versionInfo

    events:
      - http:
          path: version-info
          method: get
  screenshot:
    description: Headless Chrome Serverless-framework screenshot example
    memorySize: 1536
    timeout: 30
    handler: handlers.screenshot

    events:
      - http:
          path: screenshot
          method: get
