service: serverless-chrome-pdf

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2
  environment:
    S3_PDF_BUCKET: ${self:resources.Resources.PdfBucket.Properties.BucketName}
    CHROME_PATH: ./headless-chrome/headless_shell
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - Ref: PdfBucket
             - "/"
             - "*"
custom:
  webpackIncludeModules: false # disable auto including modules

plugins:
  - serverless-webpack

functions:
  generatePdf:
    description: Generate a PDF of a given URL using headless Chromium
    memorySize: 1536
    timeout: 120
    handler: handler.generatePdf

    events:
      - http:
          path: generate/pdf
          method: get
          response:
            headers:
              Location: integration.response.headers.location

resources:
  Resources:
    PdfBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: chrome-pdf-w7vgnbjtl3ykorcyfdxu5plapsn2da
